import MHacksImage from 'resources/images/projects/mhacks_android.png';

export default [
  {
    key: 'mhacks',
    image: MHacksImage,
    header: 'MHacks',
    description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
    skills: ['Android', 'Kotlin', 'RxJava'],
    category: 'android',
    github: 'https://github.com/mhacks/mhacks-android',
    featured: true,
  },
  {
    key: 'mhacks1',
    image: 'http://lifestyleandtravel.com/wp-content/uploads/2016/07/benjerry3.jpg',
    header: 'Ben And Jerry\'s',
    description: 'I love me some Ben\'s and Jerry\'s',
    skills: ['Ice Cream', 'Mint'],
    category: 'web_dev',
    github: 'https://github.com/mhacks/mhacks-android',
    featured: true,
  },
  {
    key: 'mhacks2',
    image: 'https://raw.githubusercontent.com/liuchengxu/img/master/space-vim/space-vim-gui.png',
    header: 'Vim',
    description: 'Vim > Emacs',
    skills: ['The', 'Best', 'Text', 'Editor'],
    category: 'ml',
    github: 'https://github.com/mhacks/mhacks-android',
    featured: true,
  },
  {
    key: 'mhacks3',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'android',
    github: 'https://github.com/mhacks/mhacks-android',
    featured: false,
  },
  {
    key: 'mhacks4',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'android',
    github: 'https://github.com/mhacks/mhacks-android',
    featured: true,
  },
  {
    key: 'mhacks5',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'ios',
    github: 'https://github.com/mhacks/mhacks-android',
    featured: false,
  },
];
