import MHacksImage from 'resources/images/projects/mhacks_android.png';

export default [
  {
    key: 'mhacks',
    image: MHacksImage,
    header: 'MHacks',
    description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'android',
    featured: true,
  },
  {
    key: 'mhacks1',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'android',
    featured: true,
  },
  {
    key: 'mhacks2',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'android',
    featured: true,
  },
  {
    key: 'mhacks3',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'android',
    featured: true,
  },
  {
    key: 'mhacks4',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'android',
    featured: true,
  },
  {
    key: 'mhacks5',
    image: MHacksImage,
    header: 'MHacks',
    description: 'Whoever',
    skills: ['Android', 'Kotlin', 'RxJava', 'Dagger'],
    category: 'ios',
    featured: true,
  },
];
